### ISSUE TITLE
Redefining constant Struct::ColInfo

### ISSUE THREAD

**Issue by franzliedke** [cxn03651/write_xlsx#110]
After the upgrade to the new 1.11.0 release (thanks!), I see a lot of warnings like these in our CI logs:

    /drone/src/vendor/bundle/ruby/3.2.0/gems/write_xlsx-1.11.0/lib/write_xlsx/worksheet.rb:360: warning: redefining constant Struct::ColInfo

The line in question also creates the same struct over and over again in a loop - this could probably be optimized:

https://github.com/cxn03651/write_xlsx/blob/38f2ab620e44653e4ea68eda19b7b87977d1379b/lib/write_xlsx/worksheet.rb#L360-L361

**Comment by cxn03651** [comment]
Thank you for your comment.

How about https://www.dropbox.com/s/xe7hqh6xnpnc3tn/write_xlsx-1.11.0.a.gem?dl=0

**Comment by cxn03651** [comment]
Sorry, I found another redefinition.

try https://www.dropbox.com/s/1hclmi09m5o2xpk/write_xlsx-1.11.0.b.gem?dl=0

**Comment by franzliedke** [comment]
@cxn03651 Thanks for the quick response!

Are these packaged gems based on a public branch on GitHub? I'd feel a bit more comfortable trying that out on a company computer. 🙈

**Comment by cxn03651** [comment]
try issue_110 branch.

https://github.com/cxn03651/write_xlsx/tree/issue_110

**Comment by grk** [comment]
@cxn03651 I checked the branch on the same codebase @franzliedke was referencing and this solves the issue, tests pass and we no longer get the warning output. Thanks for working on the fix!

**Comment by omarhassan-2016** [comment]
@cxn03651 when we expecting this to be released to main branch

**Comment by cxn03651** [comment]
sorry for the delay of fixed version's release.
v1.11.1 has been just released.
