### ISSUE TITLE
High memory usage with large datasets

### ISSUE THREAD

**Issue by Rudikza** [cxn03651/write_xlsx#24]
We are using your gem to generate fairly large XLSX files of about 400 000 rows with 5 columns and the memory usage is quite high 1.4 GB +/-.

I checked and on the original library by jmcnamara there is a constant_memory property which get's set on the worksheet. http://libxlsxwriter.github.io/working_with_memory.html

From the above page: 

The optimization works by flushing each row after a subsequent row is written. In this way the largest amount of data held in memory for a worksheet is the amount of data required to hold a single row of data.

Since each new row flushes the previous row, data must be written in sequential row order when 'constant_memory' mode is on:

```
#include "xlsxwriter.h"
int main() {
    lxw_row_t row;
    lxw_col_t col;
    lxw_row_t max_row = 1000;
    lxw_col_t max_col = 50;
    /* Set the worksheet options. */
    lxw_workbook_options options;
    options.constant_memory = 1;
    /* Create a new workbook with options. */
    lxw_workbook  *workbook  = workbook_new_opt("constant_memory.xlsx", &options);
    lxw_worksheet *worksheet = workbook_add_worksheet(workbook, NULL);
    for (row = 0; row < max_row; row++) {
        for (col = 0; col < max_col; col++) {
            worksheet_write_number(worksheet, row, col, 123.45, NULL);
        }
    }
    return workbook_close(workbook);
}
```
I would really like to help implement this feature if you could let me know if you think it's possible and if you think it's something you would look at adding in to the gem?

**Comment by cxn03651** [comment]
Hi,

I've added "optimization" option to write_xlsx.

install:
* unarchive zip file and you'll get gem file.
* gem install --local /path/to/gemfile


how to activate "optimization" option:

    workbook = WriteXLSX('huge.xlsx', optimization: true)

this version is not well tested, so be careful using this option.



[write_xlsx-0.84.1.beta.gem.zip](https://github.com/cxn03651/write_xlsx/files/290527/write_xlsx-0.84.1.beta.gem.zip)

**Comment by Rudikza** [comment]
Our use case is very simple. We are simply taking raw data and putting it in to an xlsx spreadsheet with no formatting or fancy calculations and in this case version 0.84.1 works perfectly.

**Comment by cxn03651** [comment]
thanx for your comment,

official release will be done later, because I have to write some tests to this feature.

**Comment by AlfonsoUceda** [comment]
@cxn03651 thanks for your work, I've tried the beta gem and the process creating rows is good but when you close the workbook, the memory grows until 1gb more or less. could it be reduced?

I've tried this snippet:
```ruby
workbook = WriteXLSX.new('huge.xlsx', optimization: true)
worksheet = workbook.add_worksheet

40_000.times do |row|
  500.times do |col|
    worksheet.write(row, col, "Hi Excel!")
  end
end

workbook.close
```

**Comment by cxn03651** [comment]
unfortunately I don't know how to profile memory usage of ruby script.

WriteXLSX finishes its work ( xlsx file creation ) by Workbook#close
method. So after Workbook#close, how about using GC (Garbage Collection)
like this:

    ... some work
    workbook.close

    workbook = nil
    GC.enable
    GC.start

2016-06-02 15:30 GMT+09:00 Alfonso Uceda <notifications@github.com>:
