### ISSUE TITLE
How to protect a cell?

### ISSUE THREAD

**Issue by lporras** [cxn03651/write_xlsx#38]
Hi,

I'm trying to lock a cell to not be editable, I'm following the example:
https://github.com/cxn03651/write_xlsx/blob/master/examples/protection.rb

but I don't want to protect the worksheet.  I tried to add a format for lock the cell and use that format when writing in the cell but it is still enable for editing.
 
Thanks.

**Comment by cxn03651** [comment]
I've no idea about such feature.
Could you show me xlsx file made by excel ?

**Comment by lporras** [comment]
hey @cxn03651 I found that this is not possible, excel only allows you to protect a cell if the sheet is also protected.
