### ISSUE TITLE
undefined method `get_xf_index' for arabic words

### ISSUE THREAD

**Issue by Extazystas** [cxn03651/write_xlsx#43]
I've got undefined method `get_xf_index for " صالون ومعهد هير اند مور الصحي1":String` when trying to write arabic text.
This happens when `xlsx_file.close` called. Any ideas how to handle this? 
Thanks.

**Comment by cxn03651** [comment]
Hi,

I've tested simple code below and that goes well.
check your source code saved in UTF-8.

Or send me source code which cause get_xf_index error.

    # -*- coding: utf-8 -*-
    
    require 'write_xlsx'
    
    workbook = WriteXLSX.new('arabic.xlsx')
    worksheet = workbook.add_worksheet
    worksheet.right_to_left
    worksheet.write('A1', "صالون ومعهد هير اند مور الصحي1")
    workbook.close

**Comment by Extazystas** [comment]
Hi @cxn03651, 
you right, it works! Thanks
Quick question - is there a way to send data by API like I/O stream? Have you used it for API's?

**Comment by cxn03651** [comment]
> Quick question - is there any way to send data by API like I/O stream? Have you used it for API's?

WriteXLSX#new accepts not only filename but also IO object, for example StringIO.new.
I have no idea how to use I/O stream API, but using IO object would be helpful.

**Comment by Extazystas** [comment]
@cxn03651 got it, thanks!
