### ISSUE TITLE
Number String Stored As Number instead of String

### ISSUE THREAD

**Issue by amfazlani** [cxn03651/write_xlsx#48]
Hi, thank you for this gem. I have a value that looks like a number but is actually a string datatype ( "4"). When I use the .write method it is stored as a number in excel. I am wondering if there is anyway for "4" to be stored as a string using the .write method. I would think that values with quotes are seen as text vs values without quotes are seen as number. This works with write_string but it would be cleaner if .write understood the difference between 4 and "4". ) Thank you.

**Comment by icapuccio** [comment]
Hi @amfazlani, why did you close this issue? I've encountered the same problem and don't know how to solve it transparently
