### ISSUE TITLE
when you create file with image is not filterable

### ISSUE THREAD

**Issue by nunziofiore** [cxn03651/write_xlsx#67]
To filter an excel with image we need to set property

move and size with cell
(look example https://it.extendoffice.com/documents/excel/3721-excel-filter-with-pictures.html)

The question is: is possible to add that property programmatically?

**Comment by nunziofiore** [comment]
I think you have a similar property for shape (



# OneCell or Absolute: options to move and/or size with cells.
…

)

It would be great to have one for images too

**Comment by nunziofiore** [comment]
The python version of the library can do that https://xlsxwriter.readthedocs.io/working_with_object_positioning.html?highlight=move#object-positioning-with-cell-moving-and-sizing
Do you think it's possible to make a porting of that feature?

**Comment by cxn03651** [comment]
Thanks for using write_xlsx gem.

I've implemented :object_position parameter in Worksheet#insert_image().
See https://cxn03651.github.io/write_xlsx/worksheet.html#insert_image

Update write_xlsx gem and try.

**Comment by nunziofiore** [comment]
thank you very much, I'll try this month and I will close the issue if it's ok.

**Comment by nunziofiore** [comment]
thank you very much, I'll try this month and I will open the issue if there's some trouble
