### ISSUE TITLE
Set vertical align

### ISSUE THREAD

**Issue by Souravgoswami** [cxn03651/write_xlsx#78]
By default, the vertical align is the end of each column. I want it to be centred. I tried this:
```
center = workbook.add_format
center.set_valign('center')
```

But I got no luck. Also tried `set_center_accross` and other related methods.

The source code for `set_valign()` looks like it just calls `set_align()` or acts like an alias.

Is vertically aligning a column possible?

**Comment by cxn03651** [comment]
to set vertical alignment,
use set_align('vcenter'), not set_valign()

see https://github.com/cxn03651/write_xlsx/blob/master/examples/formats.rb

//--------------------------------------------
中村 英夫
日本大学 理工学部土木工学科 教授
〒101-8308 東京都千代田区神田駿河台1-8-14
TEL 03-3259-0876  Email ***@***.***
研究室タワー・スコラ10階S1015室 https://goo.gl/maps/Ci3GAyxv1UoX7GBN7
//--------------------------------------------


2022年1月17日(月) 13:26 Sourav Goswami ***@***.***>:

**Comment by Souravgoswami** [comment]
Thank you, It works!
