### ISSUE TITLE
Number followed by newline replaces the field's data with numeric 0

### ISSUE THREAD

**Issue by Souravgoswami** [cxn03651/write_xlsx#79]
Hi, when writing to an XLSX file, any \n translates the whole field number 0 automatically. 
The string has to have a number. For example:

```
remarks = "hello world\n1234\n5678 Hello world\n"
worksheet.write(row, 4, remarks, fsize_8pt_wrapped_vtop)
```

Result:
![image](https://user-images.githubusercontent.com/37468605/153706516-e6e1985a-28df-4792-9fd9-3cdf70702f1c.png)

So the string is replaced with 0. The way to fix this is to convert \n to whitespace or something. Is there any workaround? 

Tried Onlyoffice and libreoffice to view xlsx files.

Temporary Solution:
 ``` 
 remarks.gsub!(/^\d+$/) { |x| "#{x}\s" }
```

Adding a white-space or any other characters (like \u200B) fixes the issue. But it adds the extra unwanted character.

**Comment by cxn03651** [comment]
This is a bug. Give me some time to fix it.

**Comment by cxn03651** [comment]
v1.09.2 has been released.
try it.
