### ISSUE TITLE
Possible to use multiple formats in the same cell or use template?

### ISSUE THREAD

**Issue by MyklClason** [cxn03651/write_xlsx#83]
I've started work on a project that uses this gem and a new requirement is to match the format of a template excel file and add data to the template. 

Issue is that the template has a header row with multiple styling formats within a single cell. IE: FIrst few lines of text in the string is italic, while the last line is bold. Is that possible with this (doesn't look like it)? Alternatively, is it possible to use this to edit an existing excel file (also doesn't look like it)? If not, what gem might be better suited to doing either of the two?

So a single cell might look like this (it also has a background color, but that seems easy enough):

_Some text here with **bold** in the middle_
**BOLD TEXT**

**Comment by cxn03651** [comment]
Hi, thank you for using write_xlsx gem.

Worksheet#write_rich_string might help you in this case.
see https://cxn03651.github.io/write_xlsx/worksheet.html#write_rich_string

**Comment by MyklClason** [comment]
@cxn03651 Thanks that helps a ton. Looks to be exactly what I needed.
