### ISSUE TITLE
set_column(): First column is always set to 8.43 symbols

### ISSUE THREAD

**Issue by Souravgoswami** [cxn03651/write_xlsx#84]
Hi, I want to set the size of the first column through `worksheet.set_column(row, column, column_width)`. But the library doesn't take the size for the first column only, other columns work fine.

Note that the value for `row` has to be less than 0 and column has to be 0.

Example:
```
require 'write_xlsx'

workbook = WriteXLSX.new('bug.xlsx')
worksheet = workbook.add_worksheet('1')

worksheet.write(1, 0, 'hello')
worksheet.set_column(1, 0, 30.5)

worksheet.write(1, 1, 'hello')
worksheet.set_column(1, 1, 30.5)

worksheet.write(1, 2, 'hello')
worksheet.set_column(1, 2, 30.5)

workbook.close
```
Output XLSX:
![image](https://user-images.githubusercontent.com/37468605/175423685-99970bae-b4e0-41f0-a6e0-7c1cd2834bfe.png)

Tried values like 1, 2, 3 - which didn't work. So this doesn't work either.

```
worksheet.write(2, 0, 'hello')
worksheet.set_column(2, 0, 30.5)
```
Strange that only for column 0, row number that's non-zero positive integer or floating point number doesn't work.

Workaround: I need to set the size of row 0.

**Comment by cxn03651** [comment]
Thank you for using write_xlsx.

see https://cxn03651.github.io/write_xlsx/worksheet.html#set_column
The parameters of set_column() are like this:
set_column(first_col, last_col, width, format, hidden, level, collapsed)

If you'd like to change width of column A:C to 30.5, you should write

worksheet.set_column(0, 2, 30.5) # collumn A's column number is 0, C's number is 2.
or
worksheet.set_column('A:C', 30.5)
