### ISSUE TITLE
Feature: Mixing up styles

### ISSUE THREAD

**Issue by Souravgoswami** [cxn03651/write_xlsx#85]
Is it possible to mix up the styles like bold and italics in the same cell?
For example, I have a word "Hello world", and I want to make "Hello" 12pt bold, and "world" 10pt italics.

**Comment by cxn03651** [comment]
Thank you for using write_xlsx.

Worksheet#write_rich_string is exactly what you want.
see https://cxn03651.github.io/write_xlsx/worksheet.html#write_rich_string

**Comment by Souravgoswami** [comment]
Thank you very much! It's an awesome gem with most features!
