### ISSUE TITLE
rounding up integer?

### ISSUE THREAD

**Issue by chabgood** [cxn03651/write_xlsx#90]
Hi I am writing the value 1405202108700589 and the value in the excel is 1405202108700590.  What would cause the rounding up issue?

**Comment by cxn03651** [comment]
Maximum limit of number precision is 15 digit.
This is an Excel specification.
See the NUMBER PRECISION section of the following website.
https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3

**Comment by chabgood** [comment]
Total number of characters that a cell can contain | 32,767 characters

**Comment by cxn03651** [comment]
> Total number of characters that a cell can contain | 32,767 characters

Try store 1405202108700589 in Excel application, and you will see excel cannot store 1405202108700589 exactly.
if you want to store 1405202108700589, write as string "1405202108700589", not as integer.

**Comment by chabgood** [comment]
ok so I am writing the number to 1405202108700589 string is correct, but the  number 1405202108700637 to string it is rounding up to 1405202108700640.  very strange

**Comment by cxn03651** [comment]
In my PC's excel, microsoft 365, both numbers you wrote are stored rounded up values, 1405202108700590 and 1405202108700640.
The reason for this result is probably due to Excel's specification that numbers can only be stored up to 15 digits.

**Comment by cxn03651** [comment]
if you want to store sequence of digits exactly, use write_string method and pass the digits as a string, please.
