### ISSUE TITLE
Ruby 3.2 removed Object#=~, making writing Time objects impossible

### ISSUE THREAD

**Issue by grk** [cxn03651/write_xlsx#92]
Reproduction script:

```ruby
require 'write_xlsx'

workbook = WriteXLSX.new(StringIO.new)
worksheet = workbook.add_worksheet
worksheet.write(0, 0, Time.new)
```

Since ruby 3.2 this will fail with the following error:
```
/Users/grk/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/write_xlsx-1.09.4/lib/write_xlsx/worksheet.rb:905:in `write': undefined method `=~' for 2023-01-17 21:46:17.891978 +0100:Time (NoMethodError)
```

I guess this means that there should be a should check if token respond to `=~` somewhere in the if statement in `Worksheet#write`, but I'm not sure what the correct spot would be. I could work on a PR with a solution if someone could provide some pointers.

**Comment by cxn03651** [comment]
thank you for your report!

I'll try to fix.

**Comment by grk** [comment]
Awesome, thanks!
